name: terraform-provider-confluent-internal
lang: go
lang_version: "1.23.7"
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  branches:
    - master
    - /^v\d+\.\d+\.x$/
